### ISSUE TITLE
index of BitField should be usize

### ISSUE THREAD

**Issue by kjetilkjeka** [phil-opp/rust-bit-field#11]
@blacksmithgu writes in #4 
> - The use of a u8 for the index seems arbitrary; it works fine for the existing integral types, but the trait could be made more general by using usize.

I've been using this crate a while now and everytime I'm compiling I will have some complaints about "expected u8, found usize". And when I fix the errors I still got a lot of "as u8" in the code. I think that BitField would be a lot more ergonomic to use if it were indexed by a usize was the case.

Is the choice of u8 index based upon performance? If so, maybe it would be possible to throw away everything but the lowest 8 bits just inside the function and hope the optimizer handles it? I guess it would need to be inlined as well to hope that anything happens.

**Comment by le-jzr** [comment]
I agree `usize` would be better. I assume it's `u8` simply because that's the smallest size available, and the length wasn't expected to go past 64. In terms of performance, `usize` should be just fine, if not better.

**Comment by kjetilkjeka** [comment]
@le-jzr, when you're saying just as good in performance are you assuming 32 bits arch?

I'm thinking that for certain 8-bit architectures using 16-bit addressing will make usize at least 2 bytes. Since it's an 8-bit arch (with 8-bit data bus) it would need two instructions to load from ram instead of the one needed if the index was u8, hence worse performance. Does that make sense?

**Comment by phil-opp** [comment]
> I assume it's u8 simply because that's the smallest size available, and the length wasn't expected to go past 64.

Yes, that was my reasoning. But I agree that it leads to many unnecessary casts. So `usize` might be more ergonomic, especially since most other indexing operations use `usize` too.

**Comment by kjetilkjeka** [comment]
Let me propose some alternative ways to achieve this:

1. The simple one is to switch out the type of the index from u8 to usize
2. Make the functions generic over BitField, then any BitFIeld may be used as an index.
    + (+) This is highly flexible
    + (+) Avoids breaking anything
    - (-) Might not be the most efficient as the call to .get_bit(0..8) requires bit shifting
3. Make the functions generic over a new Integer trait which will be implemented for u8/i8, u16/i16, etc, the trait need to have some as_u8() method.
   + (+) This is highly flexible
   + (+) avoids breaking anything
   + (+) will make the macro implementation of BitField be possible to do as a generic impl instead?
    - (-) Throws one more trait into the mix.
4. Make the functions generic over the (currently experimental) TryInto<u8> trait
    - (-!) This trait is currently experimental.
    - (+) All the advantages of 3 without having to include one more trait

For both 3 and 4 i would think the performance of using the functions with an u8 should be equal to what it is now?

Perhaps implementing 2 or 3 for the short run, but tracking TryFrom and implementing 4 when stabilized is the best alternative? I think this is doable without breaking anything.

**Comment by le-jzr** [comment]
@kjetilkjeka Yeah, I was thinking architectures that can work with their memory addresses efficiently. I don't think 8-bit processors warrant much attention. If you care that much about performance, you either use a wider CPU, or you write your code in assembly anyway.

**Comment by phil-opp** [comment]
We changed the index type to `usize` in #12
