### ISSUE TITLE
Support RangeInclusive

### ISSUE THREAD

**Issue by yodaldevoid** [phil-opp/rust-bit-field#21]
With `RangeInclusive` landing in Rust 1.26 I think it makes sense to support it. Personally, I think it makes sense to only use `RangeInclusive` as I have seen people define bit fields (in documentation) typically as inclusive ranges. That said, I am not sure you would want to completely break backwards compatibility, but that is your decision.

**Comment by phil-opp** [comment]
I think we should be able to support both `Range` and `RangeInclusive` through the [`RangeBounds`](https://doc.rust-lang.org/core/ops/trait.RangeBounds.html) trait. It is still unstable, but should become stable in the next release.

**Comment by phil-opp** [comment]
Implemented in https://github.com/phil-opp/rust-bit-field/pull/22
