### ISSUE TITLE
Add Security Policy

### ISSUE THREAD

**Issue by gabibguti** [phil-opp/rust-bit-field#28]
Adding a Security Policy is important to provide guidance on how users can report potential vulnerabilities and communicate when vulnerabilities will be confirmed, fixed and disclosed to the public.

This is considered a good-practice and recommended by [Github](https://docs.github.com/en/code-security/getting-started/securing-your-repository#setting-a-security-policy) and [Scorecard](https://github.com/ossf/scorecard).

If you agree, I can open a PR to suggest a Security Policy! We can then work together to communicate how the repo can best handle vulnerability reports.

##### Additional Context
Hi! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by phil-opp** [comment]
Thanks for the suggestion! I think something similar to the `x86_64` crate should work for this repo too.

It would be great if you could open a PR. Thanks!
