### ISSUE TITLE
implement BitField for slices of BitFields

### ISSUE THREAD

**Issue by kjetilkjeka** [phil-opp/rust-bit-field#8]
I feel like it would be nice to have a provided BitField implementation for slices of BitFields.

One issue will be that we can't be guaranteed that all element in the slice have the same size and would have to iterate over n-1 elements when we're setting bits in the n'th element. So setting and getting operations for the slice would be O(n).

This is not ideal since for the most cases all the elements have a constant size and we should be able to do the operations in O(1).

A way for the O(1) access time to be achievable wherever possible could be using the Sized marker trait. This is achieved by doing something in the lines of:
- A ```impl<T: BitField + Sized> T``` or ```trait BitFieldSized : BitField + Sized``` would have to be made implementing ```T::bit_length()```
- Whenever T is ```Sized+BitField```, ```self.bit_length()``` would have to return the same as ```T::bit_length()```

Implementing the O(n) algorithm would, of course, be a simpler approach and probably be "good enough".

I will be doing a simple implementation of the ```BitField``` trait for ```[BitField]``` in my own project. If this is something you desire I'm willing to coordinate it with you for upstreaming?

edit: markdown fixes

**Comment by kjetilkjeka** [comment]
Another issue I see is that the bit index is u8, this will very soon be a problem for slices of BitFields.

More generally this limit all bit fields to 256 bits in length, is that really something that is desired?

**Comment by le-jzr** [comment]
Here's my take on the matter:
https://github.com/phil-opp/rust-bit-field/issues/4#issuecomment-291468768

**Comment by phil-opp** [comment]
> One issue will be that we can't be guaranteed that all element in the slice have the same size and would have to iterate over n-1 elements when we're setting bits in the n'th element. So setting and getting operations for the slice would be O(n).

Good catch! Slices always consists of identical types (with identical size), but each entry could return a different value for `bit_length`.

> Whenever T is Sized+BitField, self.bit_length() would have to return the same as T::bit_length()

How can we guarantee this?

**Comment by le-jzr** [comment]
>> Whenever T is Sized+BitField, self.bit_length() would have to return the same as T::bit_length()

>How can we guarantee this?

I can easily imagine cases where this doesn't hold. For example, you could have a bit vector with the ability to insert and remove individual bits in the middle. Allowing partially filled buckets is an obvious way to improve performance.

**Comment by le-jzr** [comment]
Actually, no, that's dumb. I haven't thought that through very well. Ignore me. :D

**Comment by kjetilkjeka** [comment]
> > Whenever T is Sized+BitField, self.bit_length() would have to return the same as T::bit_length()

> How can we guarantee this?

I don't see any obvious (non-crazy) way to do this, but I think you might have indirectly answered the question yourself in [#4-307068848](https://github.com/phil-opp/rust-bit-field/issues/4#issuecomment-307068848).

What if a ```BitField``` is restricted to static length (changing ```self.bit_length()``` to ```T::bit_length()```)
```BitField``` may then be implemented on: (but not necessarily)
- Integer types (uX and iX)
- bool
- arrays of BitFields (with O(1) access time)

Then introduce the new trait you suggested ```BitVector``` which allows dynamic length (```self.bit_length()```). This trait may be implemented on.
- Slices of ```BitField``` (with O(1) access time)
- Slices of ```<T: BitVectors>``` (with O(n*f) access time where f is the access time for T) (not sure if this is desired though?)

Arrays of ```BitField``` can be expressed as a slice of ```BitField``` so even though ```BitVector``` is not implemented on arrays I guess it would be easy to access it as a ```BitVector```. If ```BitFIeld``` is implemented on arrays I believe it's best to avoid BitVector as well, If the array of ```BitField``` implementation is something that will be avoided, it might be a good idea to implement ```BitVector``` for arrays. It's probably best to hold on with an implementation for arrays since it's easy to use as a slice, and future use patterns of ```BitField``` and ```BitVector``` may aid that decision.

As you're writing in the earlier mentioned post, BitVectors obviously can't have the ```self.get_bits() -> Self``` since that would require way more magic than desired in a no_std crate. But BitVectors would need to have some equivalent methods.

Since BitVector will be a less flexible alternative for longer bit fields it would be justifiable to keep BitFields max length to 256 (represented by u8). In that case it might have made sense to implement ```BitField``` for:
- ```[u8, x]``` where x is in [0, 32]
- ```[u16, x]``` where x is in [0, 16]
- ```[u32, x]``` where x is in [0, 8]
- ```[u64, x]``` where x is in [0, 4]
- equivalent impl for array of integers as for array of unsigned integers
- ```[bool, x]``` where x is in [0, 256]

One last comment is that using the name ```BitVector``` might give associations to ```std::vec::Vec``` which shouldn't be viewed as an analog type. I don't know if ```BitSlice``` is better though?

So my standing at this point in summarized form is:
- Slice of BItField as BItField seems like a bad idea on second thought
- BitFields should have static length ```T::bit_length()``` instead of ```self.bit_length()```
- The BitVector suggested in [#4-307068848](https://github.com/phil-opp/rust-bit-field/issues/4#issuecomment-307068848) seems like a good idea.
- I think arrays of BitFields should be BitFields but it make sense postponing this decision until ```BitVector``` have taken form.
- ```BitVector``` might be a "bad" name, but the best alternative I can come up with is ```BitSlice```.

**Comment by kjetilkjeka** [comment]
Have a look at #10 the discussion should probably be continued there.

**Comment by phil-opp** [comment]
Closing, since we have `BitArray` now (see #10).
